### ISSUE TITLE
Some branches missed

### ISSUE THREAD

**Issue by SlimeDog** [Dudenn/TreeGravity#1]
Spigot 1.13.2
TreeGravity 3.9.1

Tree generated by
> /essentials:bigtree tree

configuration
```
Treegravity: #by Dudenn
  General:
    tgType: 4.2
    toolsAllowed:
    - GOLDEN_AXE
    - DIAMOND_AXE
    - IRON_AXE
    - STONE_AXE
    chopMethod: default
    updateChecker: false
    debugger: false
  Lumberjack:
    houseProtection: 1
    fairDurability: true
    durabilityMultiplier: 2.0
    autoReplant: false
    saplingDrop: false
```
![screen shot 2018-11-21 at 12 26 36 pm](https://user-images.githubusercontent.com/17748923/48866902-48a6e600-ed89-11e8-9307-b391bad904a4.png)
![screen shot 2018-11-21 at 12 27 34 pm](https://user-images.githubusercontent.com/17748923/48866946-6aa06880-ed89-11e8-9264-7f3436f815b5.png)
